import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, resolve } from 'node:path';
import { createInterface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { listAvailableModels } from '../agent/model-catalog.js';
import { resolveConfigPath } from '../config.js';

const DEFAULT_TRIGGER_NAME = 'Andy';
const DEFAULT_WORKING_DIR = homedir();
const DEFAULT_DATA_DIR = resolve(homedir(), '.local/share/piscord-gateway');
const DEFAULT_SESSIONS_DIR = resolve(DEFAULT_DATA_DIR, 'sessions');
const DEFAULT_DB_PATH = resolve(DEFAULT_DATA_DIR, 'gateway.db');
const AUTH_PATH = resolve(homedir(), '.pi/agent/auth.json');

export async function runSetup(args: string[]): Promise<void> {
  const tokenArg = args[0]?.trim() ?? '';
  const interactive = Boolean(process.stdin.isTTY && process.stdout.isTTY);
  const configPath = resolveConfigPath();

  printPrerequisites();

  if (!interactive && !tokenArg) {
    throw new Error('DISCORD_BOT_TOKEN must be provided as an argument when stdin is not interactive.');
  }

  let token = tokenArg;
  let triggerName = DEFAULT_TRIGGER_NAME;
  let workingDir = DEFAULT_WORKING_DIR;
  let channelPolicy: 'open' | 'open-trigger' | 'allowlist' = 'open';

  if (interactive) {
    const rl = createInterface({ input, output });

    try {
      if (!token) {
        token = await promptRequired(rl, 'Discord Bot Token');
      }

      triggerName = await promptWithDefault(rl, 'Trigger Name', DEFAULT_TRIGGER_NAME);
      workingDir = await promptWithDefault(rl, 'Working Directory', DEFAULT_WORKING_DIR);

      const policyOptions = ['open', 'open-trigger', 'allowlist'] as const;
      console.log('\nChannel Policy:');
      console.log('  1. open          — All guild channels, respond to everything');
      console.log('  2. open-trigger  — All guild channels, but require @mention');
      console.log('  3. allowlist     — Only manually registered channels');
      const policyChoice = await promptWithDefault(rl, 'Choose [1/2/3]', '1');
      const policyIndex = parseInt(policyChoice, 10) - 1;
      channelPolicy = policyOptions[policyIndex] || 'open';
    } finally {
      rl.close();
    }
  }

  if (!token) {
    throw new Error('Discord Bot Token cannot be empty.');
  }

  mkdirSync(dirname(configPath), { recursive: true });
  mkdirSync(DEFAULT_DATA_DIR, { recursive: true });
  mkdirSync(DEFAULT_SESSIONS_DIR, { recursive: true });

  writeFileSync(configPath, buildConfigFile({
    token,
    triggerName,
    workingDir,
    channelPolicy,
    sessionsDir: DEFAULT_SESSIONS_DIR,
    dbPath: DEFAULT_DB_PATH,
  }));

  console.log('\nSetup complete.');
  console.log(`Config written to: ${configPath}`);
  console.log(`Sessions directory: ${DEFAULT_SESSIONS_DIR}`);
  console.log('\nNext steps:');
  console.log('  1. piscord daemon install');
  console.log('  2. piscord daemon start');
  console.log('  3. piscord register <channel-id> "<name>" [--no-trigger | --main]');
  console.log('  4. piscord status');
}

function printPrerequisites(): void {
  console.log('Checking prerequisites...\n');

  const piPath = readCommandOutput('which pi');
  if (piPath) {
    console.log(`Pi binary: ${piPath}`);
    const piVersion = readCommandOutput('pi --version');
    console.log(`Pi version: ${piVersion || 'unknown'}`);
  } else {
    console.log('Pi binary: not found in PATH');
  }

  console.log(`Pi auth: ${existsSync(AUTH_PATH) ? `found (${AUTH_PATH})` : `missing (${AUTH_PATH})`}`);

  try {
    const models = listAvailableModels();
    console.log(`Available models: ${models.length}`);
  } catch (err) {
    console.log(`Available models: unavailable (${errorMessage(err)})`);
  }
}

async function promptRequired(rl: ReturnType<typeof createInterface>, label: string): Promise<string> {
  while (true) {
    const answer = (await rl.question(`${label}: `)).trim();
    if (answer) {
      return answer;
    }
    console.log(`${label} cannot be empty.`);
  }
}

async function promptWithDefault(
  rl: ReturnType<typeof createInterface>,
  label: string,
  defaultValue: string,
): Promise<string> {
  const answer = (await rl.question(`${label} [${defaultValue}]: `)).trim();
  return answer || defaultValue;
}

export function buildConfigFile(options: {
  token: string;
  triggerName: string;
  workingDir: string;
  channelPolicy?: 'open' | 'open-trigger' | 'allowlist';
  sessionsDir: string;
  dbPath: string;
}): string {
  return [
    '# Generated by: piscord setup',
    '# Or edit manually. See: piscord help',
    '',
    `DISCORD_BOT_TOKEN=${options.token}`,
    '',
    '# Pi agent configuration',
    'PI_BIN=pi',
    'PI_MODEL=',
    'PI_THINKING=',
    `PI_CWD=${options.workingDir}`,
    'PI_EXTRA_FLAGS=',
    '',
    '# Gateway behavior',
    `TRIGGER_NAME=${options.triggerName}`,
    'MAX_CONCURRENCY=3',
    'MAX_SCHEDULED_CONCURRENCY=1',
    'POLL_INTERVAL_MS=1000',
    'SHUTDOWN_TIMEOUT_MS=15000',
    'AUTO_REGISTER_DMS=true',
    `CHANNEL_POLICY=${options.channelPolicy ?? 'open'}`,
    'EXCLUDED_CHANNELS=',
    'MAX_ATTACHMENT_BYTES=26214400',
    'MAX_TOTAL_ATTACHMENT_BYTES=52428800',
    '',
    '# Archive',
    'ARCHIVE_RETENTION_DAYS=30',
    '',
    '# Storage',
    `SESSIONS_DIR=${options.sessionsDir}`,
    'ARCHIVE_RETENTION_DAYS=30',
    `DB_PATH=${options.dbPath}`,
    '',
    '# Logging',
    'LOG_LEVEL=info',
    '',
  ].join('\n');
}

function readCommandOutput(command: string): string | undefined {
  try {
    return execSync(command, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim() || undefined;
  } catch {
    return undefined;
  }
}

function errorMessage(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}
